version: 2
before:
  hooks:
    - go mod download
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/carapace-pnpm
    binary: carapace-pnpm
archives:
  - id: default
    ids:
     - default
    format_overrides:
      - goos: windows
        formats: [zip]
